services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    env_file:
      - docker.env
    ports:
      - "27017:27017"
  # restart: always
volumes:
  mongodb_data:
