name: Note App backend build and deploy

on:
  push:
    branches:
      - 'main'
jobs:
  test_build_deploy:
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        working-directory: ./backend
    env:
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      DB_URL: ${{secrets.DB_URL}}
      USER_NAME: ${{secrets.USER_NAME}}
      SSH_HOST: ${{secrets.SSH_HOST}}
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: use node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm test
      - name: build
        run: npm run build
      - name: Archive Production Artifact
        run: tar -czvf build.tar.gz ./dist
      - name: copy dist file to ec2 server
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          # Create the directory on the server
          echo "ssh to server to confirm dist folder exist"
          ssh -o StrictHostKeyChecking=no -i private_key $USER_NAME@$SSH_HOST "mkdir -p /home/$USER_NAME/NoteApp/backend/dist"

          # Now copy the files using scp with recursive copy
          echo "scp to server to copy build folder"
          scp -o StrictHostKeyChecking=no -r -i private_key dist/* $USER_NAME@$SSH_HOST:/home/$USER_NAME/NoteApp/backend/dist

          #Now handle all the steps for new code deploy to server
          ssh -o StrictHostKeyChecking=no -i private_key $USER_NAME@$SSH_HOST << 'EOF'

          echo "cd /home/'$USER_NAME'/NoteApp/backend"
          pwd

          EOF
    
