name: Note App backend build and deploy

on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: use node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm test
      - name: build
        run: npm run build